const conversionRate = 83; // Example conversion rate from USD to INR

const shoesArray = [
    {
      id: 1,
      brand: "Nike",
      model: "Air Max 270",
      size: [7, 8, 9, 10],
      color: "Black/White",
      price: 150 * conversionRate,
      inStock: "in Stock",
      categories: ["Running", "Casual"],
      rating: 4.7,
      reviewsCount: 2500,
      images: "images/1.webp",
    },
    {
      id: 2,
      brand: "Adidas",
      model: "Ultraboost 21",
      size: [6, 7, 8, 9, 10],
      color: "Core Black",
      price: 180 * conversionRate,
      inStock: "in Stock",
      categories: ["Running", "Sport"],
      rating: 4.8,
      reviewsCount: 3400,
      images: "images/2.webp",
    },
    {
      id: 3,
      brand: "Puma",
      model: "RS-X³",
      size: [7, 8, 9, 10],
      color: "White/Grey",
      price: 120 * conversionRate,
      inStock: "in Stock",
      categories: ["Casual", "Streetwear"],
      rating: 4.5,
      reviewsCount: 1800,
      images: "images/3.webp",
    },
    {
      id: 4,
      brand: "Reebok",
      model: "Club C 85",
      size: [6, 7, 8, 9, 10],
      color: "White/Green",
      price: 75 * conversionRate,
      inStock: "in Stock",
      categories: ["Tennis", "Casual"],
      rating: 4.6,
      reviewsCount: 2200,
      images: "images/4.webp",
    },
    {
      id: 5,
      brand: "New Balance",
      model: "574",
      size: [8, 9, 10, 11],
      color: "Grey/White",
      price: 80 * conversionRate,
      inStock: "in Stock",
      categories: ["Lifestyle", "Casual"],
      rating: 4.4,
      reviewsCount: 1500,
      images: "images/5.webp",
    },
    {
      id: 6,
      brand: "Asics",
      model: "Gel-Kayano 27",
      size: [7, 8, 9, 10, 11],
      color: "Blue/White",
      price: 160 * conversionRate,
      inStock: "in Stock",
      categories: ["Running", "Sport"],
      rating: 4.7,
      reviewsCount: 2900,
      images: "images/6.webp",
    },
    {
      id: 7,
      brand: "Converse",
      model: "Chuck Taylor All Star",
      size: [6, 7, 8, 9],
      color: "Black/White",
      price: 55 * conversionRate,
      inStock: "in Stock",
      categories: ["Casual", "Streetwear"],
      rating: 4.5,
      reviewsCount: 3200,
      images: "images/7.webp",
    },
    {
      id: 8,
      brand: "Vans",
      model: "Old Skool",
      size: [7, 8, 9, 10, 11],
      color: "Black/White",
      price: 65 * conversionRate,
      inStock: "in Stock",
      categories: ["Casual", "Skateboarding"],
      rating: 4.6,
      reviewsCount: 2100,
      images: "images/8.webp",
    },
    {
      id: 9,
      brand: "Jordan",
      model: "Air Jordan 1",
      size: [8, 9, 10, 11, 12],
      color: "Red/White",
      price: 170 * conversionRate,
      inStock: "in Stock",
      categories: ["Basketball", "Casual"],
      rating: 4.8,
      reviewsCount: 4000,
      images: "images/9.webp",
    },
    {
      id: 10,
      brand: "Under Armour",
      model: "Curry 8",
      size: [7, 8, 9, 10],
      color: "White/Gold",
      price: 160 * conversionRate,
      inStock: "in Stock",
      categories: ["Basketball", "Sport"],
      rating: 4.7,
      reviewsCount: 2600,
      images: "images/10.webp",
    }
];

console.log(shoesArray);
